### ISSUE TITLE
incorrect explanation for the associativity of `a <$> b <$> c`

### ISSUE THREAD

**Issue by zh217** [JakeWheat/intro_to_parsing#3]
line 196 of ApplicativeStyle.lhs claims that
```
a <$> b <$> c
```
is parsed as
```
a <$> (b <$> c)
```

This is incorrect:

```
λ> :info (<$>)
(<$>) :: Functor f => (a -> b) -> f a -> f b
  	-- Defined in ‘Data.Functor’
infixl 4 <$>
```

It actually associates to the left. However here it doesn't matter, since we have

```
instance Functor ((->) r) -- Defined in ‘GHC.Base’
```

So essentially we are writing
```
(a . b) <$> c
```
which is the same as
```
a <$> (b <$> c)
```
due to functor law.

**Comment by JakeWheat** [comment]
Fixed in this commit, 8b6ea739b445137ea4eedaa543f6ee80564d4423 , sorry for the delay!
