### ISSUE TITLE
Typo in 3.6.1

### ISSUE THREAD

**Issue by luisggpina** [JakeWheat/intro_to_parsing#9]
Following 3.6.1 as it is results in:

```
*Main> regularParse simpleExpr5 "(1+a)"
Left (line 1, column 3):
unexpected "+"
expecting digit or ")"
```

The expected is:

```
*Main> parseWithWhitespace simpleExpr5 "(1+a)"
Right (Parens (Add (Num 1) (Var "a")))
```

I think this happens because:

```
term5 :: Parser SimpleExpr 
term5 = term term5

simpleExpr5 :: Parser SimpleExpr
simpleExpr5 = try addE5 <|> term5
```

`term5` doesn't know how to parse additions, but `simpleExpr5` does.  When parsing `(1+2)`, `addE5` fails and lets `term5` try, which parses the parentheses.  But then `term5` cannot parse the sub-expression `1+2`, hence the error.

On my side, I was able to fix this by doing:

```
term5 :: Parser SimpleExpr 
term5 = term simpleExpr5
```

Is this the correct/most elegant fix?

Thanks for putting together such a well-written tutorial on parsec!

**Comment by JakeWheat** [comment]
Thanks for the report. Sorry for the slowest response ever! I'll take a closer look.

**Comment by JakeWheat** [comment]
Hi Xhliu,

Thanks for the report. I took a quick look, and I think this is a intended limitation of the parser at this stage of the tutorial (it's been a while). I think your suggestion to use 'term5 = term simpleExpr5' is the correct way to fix this limitation, and this is the approach taken later on in the tutorial.
If I can find the time to get my head back into the tutorial here, I will see if I can find a way to make this less confusing, but nothing is obvious to me right now.
Thanks.

**Comment by JakeWheat** [comment]
I took a closer look, and I think you are right about this. It looks like it was just a typo that's been there a long time. Thanks for the report.
